package drools.spring.rules;
import drools.spring.example.model.DiseaseInput;
rule "GetSymptomsPrehlada"
    agenda-group "bolesti"
    when
        $di: DiseaseInput(disease.name == "Prehlada")
    then
        $di.addNewSymptom("Curenje iz nosa");
        $di.addNewSymptom("Bol u grlu");
        $di.addNewSymptom("Glavobolja");
        $di.addNewSymptom("Kijanje");
        $di.addNewSymptom("Kašalj");
end

rule "GetSymptomsGroznica"
    agenda-group "bolesti"
    when
        $di: DiseaseInput(disease.name == "Groznica")
    then
        $di.addNewSymptom("Curenje iz nosa");
        $di.addNewSymptom("Bol u grlu");
        $di.addNewSymptom("Glavobolja");
        $di.addNewSymptom("Kijanje");
        $di.addNewSymptom("Kašalj");
        $di.addNewSymptom("Drhtavica");
        $di.addNewSymptom("Temperatura veca od 38 0C");
end

rule "GetSymptomsUK"
    agenda-group "bolesti"
    when
        $di: DiseaseInput(disease.name == "Upala krajnika")
    then
        $di.addNewSymptom("Bol koji se siri do usiju");
        $di.addNewSymptom("Bol u grlu");
        $di.addNewSymptom("Glavobolja");
        $di.addNewSymptom("Gubitak apetita");
        $di.addNewSymptom("Umor");
        $di.addNewSymptom("Zuti sekret iz nosa");
        $di.addNewSymptom("Drhtavica");
        $di.addNewSymptom("Temperatura od 40 0C do 41 0C");
end

rule "GetSymptomsSI"
    agenda-group "bolesti"
    when
        $di: DiseaseInput(disease.name == "Sinusna infekcija")
    then
        $di.addNewSymptom("Specifični zahtev, u kartonu (sitemu) treba da stoji da je pacijent bolovao od prehlade ili " +
                           "groznice u poslednjih 60 dana.");
        $di.addNewSymptom("Kasalj");
        $di.addNewSymptom("Temperatura veca od 38 0C");
        $di.addNewSymptom("Bol u grlu");
        $di.addNewSymptom("Zuti sekret iz nosa");
        $di.addNewSymptom("Glavobolja");
        $di.addNewSymptom("Oticanje oko ociju");
end

rule "GetSymptomsHT"
    agenda-group "bolesti"
    when
        $di: DiseaseInput(disease.name == "Hipertenzija")
    then
        $di.addNewSymptom("U poslednjih 6 meseci zabelezeno barem 10 slucajeva u kojem je pacijent imao visok pritisak.");
end

rule "GetSymptomsDij"
    agenda-group "bolesti"
    when
        $di: DiseaseInput(disease.name == "Dijabetes")
    then
        $di.addNewSymptom("Cesto uriniranje");
        $di.addNewSymptom("Gubitak telesne tezine");
        $di.addNewSymptom("Zamor");
        $di.addNewSymptom("Mucnina i povracanje");
end

rule "GetSymptomsHbb"
    agenda-group "bolesti"
    when
        $di: DiseaseInput(disease.name == "Hronicna bubrezna bolest")
    then
        $di.addNewSymptom("*Pacijent boluje od dijabetesa");
        $di.addNewSymptom("*Pacijent boluje od hipertenzije vise od 6 meseci");
        $di.addNewSymptom("Bol u grudima");
        $di.addNewSymptom("Gusenje");
        $di.addNewSymptom("Otoci nogu i zglobova");
        $di.addNewSymptom("Nocturia");
        $di.addNewSymptom("Zamor");
end

rule "GetSymptomsAbp"
    agenda-group "bolesti"
    when
        $di: DiseaseInput(disease.name == "Akutna bubrezna povreda")
    then
        $di.addNewSymptom("*Oporavlja se od operacije");
        $di.addNewSymptom("*U poslednjih 14 dana dijagnostikovana bolest koja kao simptom ima povišenu telesnu " +
                           "temperaturu");
        $di.addNewSymptom("*U poslednjih 21 dana dijagnostikovana bolest za koju je primao antibiotike");
        $di.addNewSymptom("Dijareja");
        $di.addNewSymptom("Otoci nogu i zglobova");
        $di.addNewSymptom("Gusenje");
        $di.addNewSymptom("Zamor");
end
